version: '3'
services:
  koa:
    build:
      context: ./koa
  testcafe:
    build:
      context: ./testcafe
    depends_on:
      - koa
    command: >
      "chromium:headless --no-sandbox"
      /var/src/test/tests/*
      -s /var/src/test/screenshots
