version: '3'
services:
  koa:
    build:
      context: ./koa
  testcafe:
    build:
      context: ./testcafe
    depends_on:
      - koa
    command: '"chromium --no-sandbox" /var/src/test/tests/*'
