version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.2
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - docker-koa-{{ checksum "koa/Dockerfile" }}-{{ checksum "koa/package.json" }}
          - docker-koa
      - restore_cache:
          keys:
            - docker-testcafe-{{ checksum "testcafe/Dockerfile" }}-{{ checksum "testcafe/package.json" }}
            - docker-testcafe
      - run: if test -d ~/repo/.circleci/cache; then \
               docker load -i ~/repo/.circleci/cache/docker-koa.tar; \
               docker load -i ~/repo/.circleci/cache/docker-testcafe.tar \
             fi

      - run: docker-compose -f docker-compose.test.yml build
      - run: mkdir -p ~/repo/.circleci/cache \
             && docker save -o ~/repo/circleci/cache/docker-koa.tar \
             && docker save -o ~/repo/circleci/cache/docker-testcafe.tar
      - save_cache:
          paths:
            - ~/repo/circleci/cache/docker-koa.tar
          key: docker-koa-{{ checksum "koa/Dockerfile" }}-{{ checksum "koa/package.json" }}
      - save_cache:
          paths:
            - ~/repo/circleci/cache/docker-testface.tar
          key: docker-koa-{{ checksum "testcafe/Dockerfile" }}-{{ checksum "testcafe/package.json" }}
      - run: docker-compose -f docker-compose.test.yml run testcafe
